"""unique keys upgrade

Revision ID: 7137f7826dd8
Revises: 8d97dcedfe47
Create Date: 2021-11-27 17:00:17.188480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7137f7826dd8'
down_revision = '8d97dcedfe47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_endereco_CEP', table_name='endereco')
    op.create_index(op.f('ix_endereco_CEP'), 'endereco', ['CEP'], unique=False)
    op.drop_index('ix_endereco_complemento', table_name='endereco')
    op.create_index(op.f('ix_endereco_complemento'), 'endereco', ['complemento'], unique=False)
    op.drop_index('ix_endereco_estado', table_name='endereco')
    op.create_index(op.f('ix_endereco_estado'), 'endereco', ['estado'], unique=False)
    op.drop_index('ix_endereco_municipio', table_name='endereco')
    op.create_index(op.f('ix_endereco_municipio'), 'endereco', ['municipio'], unique=False)
    op.drop_index('ix_endereco_numero', table_name='endereco')
    op.create_index(op.f('ix_endereco_numero'), 'endereco', ['numero'], unique=False)
    op.drop_index('ix_endereco_pais', table_name='endereco')
    op.create_index(op.f('ix_endereco_pais'), 'endereco', ['pais'], unique=False)
    op.drop_index('ix_endereco_rua', table_name='endereco')
    op.create_index(op.f('ix_endereco_rua'), 'endereco', ['rua'], unique=False)
    op.drop_index('ix_usuario_nome', table_name='usuario')
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.create_index('ix_usuario_nome', 'usuario', ['nome'], unique=False)
    op.drop_index(op.f('ix_endereco_rua'), table_name='endereco')
    op.create_index('ix_endereco_rua', 'endereco', ['rua'], unique=False)
    op.drop_index(op.f('ix_endereco_pais'), table_name='endereco')
    op.create_index('ix_endereco_pais', 'endereco', ['pais'], unique=False)
    op.drop_index(op.f('ix_endereco_numero'), table_name='endereco')
    op.create_index('ix_endereco_numero', 'endereco', ['numero'], unique=False)
    op.drop_index(op.f('ix_endereco_municipio'), table_name='endereco')
    op.create_index('ix_endereco_municipio', 'endereco', ['municipio'], unique=False)
    op.drop_index(op.f('ix_endereco_estado'), table_name='endereco')
    op.create_index('ix_endereco_estado', 'endereco', ['estado'], unique=False)
    op.drop_index(op.f('ix_endereco_complemento'), table_name='endereco')
    op.create_index('ix_endereco_complemento', 'endereco', ['complemento'], unique=False)
    op.drop_index(op.f('ix_endereco_CEP'), table_name='endereco')
    op.create_index('ix_endereco_CEP', 'endereco', ['CEP'], unique=False)
    # ### end Alembic commands ###
