"""tabela endereco

Revision ID: 8d97dcedfe47
Revises: f4850da7e30e
Create Date: 2021-11-23 09:36:45.873250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d97dcedfe47'
down_revision = 'f4850da7e30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=64), nullable=True),
    sa.Column('CEP', sa.String(length=8), nullable=True),
    sa.Column('rua', sa.String(length=64), nullable=True),
    sa.Column('numero', sa.String(length=64), nullable=True),
    sa.Column('complemento', sa.String(length=64), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endereco_CEP'), 'endereco', ['CEP'], unique=True)
    op.create_index(op.f('ix_endereco_complemento'), 'endereco', ['complemento'], unique=True)
    op.create_index(op.f('ix_endereco_estado'), 'endereco', ['estado'], unique=True)
    op.create_index(op.f('ix_endereco_municipio'), 'endereco', ['municipio'], unique=True)
    op.create_index(op.f('ix_endereco_numero'), 'endereco', ['numero'], unique=True)
    op.create_index(op.f('ix_endereco_pais'), 'endereco', ['pais'], unique=True)
    op.create_index(op.f('ix_endereco_rua'), 'endereco', ['rua'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endereco_rua'), table_name='endereco')
    op.drop_index(op.f('ix_endereco_pais'), table_name='endereco')
    op.drop_index(op.f('ix_endereco_numero'), table_name='endereco')
    op.drop_index(op.f('ix_endereco_municipio'), table_name='endereco')
    op.drop_index(op.f('ix_endereco_estado'), table_name='endereco')
    op.drop_index(op.f('ix_endereco_complemento'), table_name='endereco')
    op.drop_index(op.f('ix_endereco_CEP'), table_name='endereco')
    op.drop_table('endereco')
    # ### end Alembic commands ###
