"""tabela usuarios

Revision ID: f4850da7e30e
Revises: 
Create Date: 2021-11-23 09:35:40.949500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4850da7e30e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('CPF', sa.String(length=11), nullable=True),
    sa.Column('PIS', sa.String(length=11), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_CPF'), 'usuario', ['CPF'], unique=True)
    op.create_index(op.f('ix_usuario_PIS'), 'usuario', ['PIS'], unique=True)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_PIS'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_CPF'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
